### ISSUE TITLE
Error contacting DeepL API: 403: Forbidden

### ISSUE THREAD

**Issue by darkseji** [ychoi-kr/omegat-plugin-deepl-api-free#2]
Hi,

I'm trying out the plugin but unfortunately the only thing I'm getting is "Error contacting DeepL API: 403: Forbidden" error message. OT v6.0. Let me know how I can troubleshoot or what to check.

**Comment by ychoi-kr** [comment]
Please check if your API key is valid.

Below is from the DeepL website:

Error 403
Authorization failed. Please supply a valid auth_key parameter

This error occurs when the API key in the request is either missing or incorrect.

For the API key to be valid, your subscription must be active. You can check your API key and the status of your subscription in your DeepL account, under API keys.

Please also check that you have the correct subscription plan for the usage you require. To get access to DeepL's API, you need to subscribe to the DeepL API plan. The authentication key for CAT tools is included in the DeepL Pro Advanced and DeepL Pro Ultimate subscription plans.

**Comment by darkseji** [comment]
Ah, I get it. I thought that it was a workaround to use the free plan only - I don't have a paid subscription.
