### ISSUE TITLE
Api key configuration in Linux?

### ISSUE THREAD

**Issue by afduggirala** [ychoi-kr/omegat-plugin-deepl-api-free#4]
Hello,

The instructions clearly state where one needs to add the api key text in Windows and Mac.
Where do I put it when working on Linux?

thank you,

**Comment by ychoi-kr** [comment]
Hello,

Thank you for your inquiry about the DeepL API Free Plug-in for OmegaT.

I primarily use Windows, so I haven't personally tested the installation process on Linux. However, based on available information, you can try the following steps to configure the API key on Linux:

1. Copy the plug-in file to OmegaT's plugins directory. For example, if OmegaT is installed in `/opt/omegat/`, you can use the following command:
    ```bash
    sudo cp your-plugin-file.jar /opt/omegat/OmegaT-default/plugins/
    ```

2. Set the API key as an environment variable. You can do this each time you run OmegaT by using the following command:
    ```bash
    java -Ddeepl-api-free.api.key=YOURAPIKEY -jar /opt/omegat/OmegaT-default/OmegaT.jar
    ```

    Alternatively, you can add the API key to your `.bashrc` file to set it permanently. Add the following line to your `.bashrc` file:
    ```bash
    export JAVA_OPTS="-Ddeepl-api-free.api.key=YOURAPIKEY"
    ```

    Then, reload the `.bashrc` file to apply the changes:
    ```bash
    source ~/.bashrc
    ```

    After this, you can run OmegaT with:
    ```bash
    java $JAVA_OPTS -jar /opt/omegat/OmegaT-default/OmegaT.jar
    ```

Please try these steps and let me know if you encounter any issues. Your feedback would be greatly appreciated, as it will help improve the instructions for other Linux users.
